### ISSUE TITLE
Unsupported relocation: ARM64_RELOC_PAGEOFF12 on macho object file

### ISSUE THREAD

**Issue by banxian** [Vector35/arch-arm64#71]
I loaded some macho-64 object file (compile from c to .s by obfuscator-llvm first, with some minor change, then compile by apple clang).
when I load one of these file into binary ninja, I see such a warning in logs.
same file can loaded in to IDA pro without relocation error.
the object file is used in commercial projects so I can't attach it but I think it's easy to write a relocation test case for this bug

**Comment by lwerdna** [comment]
@banxian If you have any tips on getting an ARM64_RELOC_PAGEOFF12 into an executable or .so at different addresses, I could use them for additional testing. I moved the one around in the fakeintrinsics_bn_64.s you provided by inserting some nops between the adrp/add and the gBase64Table() and everything seems to work ok.

**Comment by lwerdna** [comment]
Verified ARM64_RELOC_PAGEOFF12, but it doesn't always work with the ADRP it always follows, which spawned the following issue:

https://github.com/Vector35/arch-arm64/issues/73

This issue has a demonstration object attached. Please continue discussion there.

**Comment by cimcgee** [comment]
If you can't get past the _f12 problem than give it back to me so I can make some $/ and there is no 21/28 problem lol...this is why I said the whole time mycode is bullet proof! You are just giving up to early so I think I'ma whatch you All flail and implicate yourselves further to the full extent! Whooaaa I've been eating a long time for this and I already started calling the authorities last week! I've know what my UID # has been for some time now and I can allwYs make it work better than a computer.....Base ten y'all come on now why do you think it's as important as it is....the math can not be figured out on a computer! That's why Space And Time means so much to me even if it works with out that knowledge it's limited at best! It is totally proprietary to me 100%. And you won't get it authenticared ever for one very clever and sneaky way that I got away with as it was being stripped from me! Oh yeah JI everyone!!!!
